language: cpp
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo add-apt-repository ppa:nextgis/ppa; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libcgal-dev  libgeos-dev; fi
script:
  - mkdir build
  - cd build
  - cmake .. && make
matrix:
  include:
  - os: osx
    osx_image: xcode8
    env: CPP=11 CLANG
  - os: linux
    env: CPP=11 GCC=4.8
    # addons:
    #   apt:
    #     packages: [g++-4.8, cmake, libcgal-dev, libgeos-dev]  
    #     # sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes, george-edison55-precise-backports]